services:
  relayer:
    image: iconcommunity/centralized-relay:${RELAYER_IMAGE_VERSION:-latest}
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - ${CONFIG}/relayer:/home/${RELAYER_USER:-relayer}/.centralized-relay:Z
      - ${CONFIG_PATH:-./config.yaml}:/home/${RELAYER_USER:-relayer}/config.yaml:ro
    labels:
      service: "centralized-relay"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - SOCKET_PATH=${SOCKET_PATH:-/home/${RELAYER_USER:-relayer}/.centralized-relay/relay.sock}
    networks:
      relayer:
  dashboard:
    image: iconcommunity/relay-admin-dashboard:${DASHBOARD_IMAGE_VERSION:-latest}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - ${SERVICE_PORT:-3000}
    volumes:
      - ${SOCKET_PATH:-${CONFIG}/relayer/.centralized-relay/relay.sock}:/tmp/relay.sock
      - ${USERS_LIST_FILE_PATH:-./users.json}:/home/dashboard/users.json:ro
      - ${RELAYERS_LIST_FILE_PATH:-./relayers.json}:/home/dashboard/relayer.json:ro
    labels:
      service: "admin-dashboard"
    environment:
      - PORT=${SERVICE_PORT:-3000}
      - NEXT_PUBLIC_APP_API_ENDPOINT=${NEXT_PUBLIC_APP_API_ENDPOINT:-http://localhost:3000/api}
      - NEXT_PUBLIC_API_RETRY_INTERVAL_IN_SECONDS=${NEXT_PUBLIC_API_RETRY_INTERVAL_IN_SECONDS:-5}
      - NEXT_PUBLIC_API_MAX_RETRY=${NEXT_PUBLIC_API_MAX_RETRY:-5}
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - NEXT_XCALLSCAN_BASE_URL=${NEXT_XCALLSCAN_BASE_URL:-https://xcallscan.xyz/api}
      - NEXT_RELAYER_SOCKET_PATH=/tmp/relay.sock
    depends_on:
      - relayer
    networks:
      relayer:
  web:
    image: iconcommunity/admin-dashboard-nginx:${NGINX_IMAGE_VERSION:-latest}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ${CONFIG}/web:/config:Z
      - ${CONFIG}/web/crontabs:/var/spool/cron/crontabs:Z
    labels:
      service: "nginx-web"
    environment:
      - ENABLE_LETSENCRYPT
      - SERVICE_HOST=${SERVICE_HOST:-http://dashboard:${SERVICE_PORT:-3000}}
      - LETSENCRYPT_USE_STAGING=${LETSENCRYPT_USE_STAGING:-1}
      - LETSENCRYPT_DOMAIN
    depends_on:
      - dashboard
    networks:
      relayer:
networks:
  relayer:
