name: Build and Push

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: ./base
          load: true
          tags: iconcommunity/relay-base:latest
      - name: Build relayer image
        uses: docker/build-push-action@v6
        with:
          context: ./relayer
          load: true
          tags: iconcommunity/centralized-relay:latest
      - name: Build nginx image
        uses: docker/build-push-action@v6
        with:
          context: ./web
          load: true
          tags: iconcommunity/relay-admin-dashboard:latest
